# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Account(object):

    def addwindow(self):
        self.Add.show()
        self.Main.hide()

    def remwindow(self):
        self.Remove.show()
        self.Main.hide()

    def back(self):
        self.Add.hide()
        self.Remove.hide()
        self.Main.show()

    def test(self):
        print(self.combo_rem_user.currentText())

    def addacc(self):
        getuser=self.line_add_user.text()
        getpass=self.line_add_pass.text()
        fadmin=open("AdminLogin.txt",'r+')
        userlist=[]
        for line in fadmin:
            user_txt,pass_txt=line.split("|")
            userlist.append(user_txt)
        if (getuser in userlist):
            self.label_add_disp.setText("Username already exists")
        else:
            fadmin.write(getuser+"|"+getpass+"\n")
            self.label_add_disp.setText("Successfully Added")
        fadmin.close()


    def setupUi(self, Account):
        Account.setObjectName("Account")
        Account.resize(541, 555)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Account.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Account)
        self.centralwidget.setObjectName("centralwidget")
        self.Main = QtWidgets.QFrame(self.centralwidget)
        self.Main.setGeometry(QtCore.QRect(0, 0, 541, 571))
        self.Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Main.setObjectName("Main")
        self.but_add = QtWidgets.QPushButton(self.Main)
        self.but_add.setGeometry(QtCore.QRect(170, 140, 211, 41))
        self.but_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.but_add.setObjectName("but_add")
        self.but_add.clicked.connect(self.addwindow)
        self.but_rem = QtWidgets.QPushButton(self.Main)
        self.but_rem.setGeometry(QtCore.QRect(170, 320, 211, 41))
        self.but_rem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.but_rem.setObjectName("but_rem")
        self.but_rem.clicked.connect(self.remwindow)
        #Add Account Page
        self.Add = QtWidgets.QFrame(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(0, 0, 541, 531))
        self.Add.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Add.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Add.setObjectName("Add")
        self.Add.hide()
        self.label = QtWidgets.QLabel(self.Add)
        self.label.setGeometry(QtCore.QRect(60, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.Add)
        self.label_3.setGeometry(QtCore.QRect(70, 280, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.but_addacc = QtWidgets.QPushButton(self.Add)
        self.but_addacc.setGeometry(QtCore.QRect(234, 402, 101, 41))
        self.but_addacc.setObjectName("but_addacc")
        self.but_addacc.clicked.connect(self.addacc)
        self.but_back = QtWidgets.QPushButton(self.Add)
        self.but_back.setGeometry(QtCore.QRect(424, 472, 91, 31))
        self.but_back.setObjectName("but_back")
        self.but_back.clicked.connect(self.back)
        self.label_8 = QtWidgets.QLabel(self.Add)
        self.label_8.setGeometry(QtCore.QRect(150, 40, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.line_add_user = QtWidgets.QLineEdit(self.Add)
        self.line_add_user.setGeometry(QtCore.QRect(250, 149, 231, 31))
        self.line_add_user.setObjectName("line_add_user")
        self.line_add_pass = QtWidgets.QLineEdit(self.Add)
        self.line_add_pass.setGeometry(QtCore.QRect(250, 280, 231, 31))
        self.line_add_pass.setObjectName("line_add_pass")
        self.line_add_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_add_disp = QtWidgets.QLabel(self.Add)
        self.label_add_disp.setGeometry(QtCore.QRect(146, 349, 301, 31))
        self.label_add_disp.setText("")
        self.label_add_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_disp.setObjectName("label_add_disp")
        #Add Remove Page
        self.Remove = QtWidgets.QFrame(self.centralwidget)
        self.Remove.setGeometry(QtCore.QRect(0, 0, 541, 531))
        self.Remove.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Remove.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Remove.setObjectName("Remove")
        self.Remove.hide()
        self.label_4 = QtWidgets.QLabel(self.Remove)
        self.label_4.setGeometry(QtCore.QRect(60, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.combo_rem_user = QtWidgets.QComboBox(self.Remove)
        self.combo_rem_user.setGeometry(QtCore.QRect(280, 150, 211, 31))
        self.combo_rem_user.setEditable(True)
        self.combo_rem_user.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.combo_rem_user.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.combo_rem_user.setObjectName("comboBox")
        fhand=open("AdminLogin.txt",mode='r')
        for line in fhand:
            user_txt,pass_txt=line.split("|")
            self.combo_rem_user.addItem(user_txt)
        self.label_5 = QtWidgets.QLabel(self.Remove)
        self.label_5.setGeometry(QtCore.QRect(70, 280, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Remove)
        self.label_6.setGeometry(QtCore.QRect(150, 40, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Remove)
        self.label_7.setGeometry(QtCore.QRect(160, 220, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.but_rem_2 = QtWidgets.QPushButton(self.Remove)
        self.but_rem_2.setGeometry(QtCore.QRect(220, 410, 101, 41))
        self.but_rem_2.setObjectName("but_rem_2")
        self.but_rem_2.clicked.connect(self.test)
        self.lineEdit = QtWidgets.QLineEdit(self.Remove)
        self.lineEdit.setGeometry(QtCore.QRect(280, 290, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.line_rem_pass = QtWidgets.QLineEdit(self.Remove)
        self.line_rem_pass.setGeometry(QtCore.QRect(280, 290, 211, 31))
        self.line_rem_pass.setObjectName("line_rem_pass")
        self.but_back_2 = QtWidgets.QPushButton(self.Remove)
        self.but_back_2.setGeometry(QtCore.QRect(430, 470, 91, 31))
        self.but_back_2.setObjectName("but_back_2")
        self.but_back_2.clicked.connect(self.back)
        self.label_add_disp_2 = QtWidgets.QLabel(self.Remove)
        self.label_add_disp_2.setGeometry(QtCore.QRect(120, 350, 301, 31))
        self.label_add_disp_2.setText("")
        self.label_add_disp_2.setObjectName("label_add_disp_2")
        Account.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Account)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menubar.setObjectName("menubar")
        Account.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Account)
        self.statusbar.setObjectName("statusbar")
        Account.setStatusBar(self.statusbar)

        self.retranslateUi(Account)
        QtCore.QMetaObject.connectSlotsByName(Account)

    def retranslateUi(self, Account):
        _translate = QtCore.QCoreApplication.translate
        Account.setWindowTitle(_translate("Account", "MainWindow"))
        self.but_add.setText(_translate("Account", "Add Account"))
        self.but_rem.setText(_translate("Account", "Remove Account"))
        self.label.setText(_translate("Account", "Username:"))
        self.label_3.setText(_translate("Account", "Password:"))
        self.but_addacc.setText(_translate("Account", "ADD"))
        self.but_back.setText(_translate("Account", "Back"))
        self.label_8.setText(_translate("Account", "ADD"))
        self.label_4.setText(_translate("Account", "Username:"))
        self.combo_rem_user.setCurrentText(_translate("Account", "Select Username"))
        self.label_5.setText(_translate("Account", "Password:"))
        self.label_6.setText(_translate("Account", "REMOVE"))
        self.label_7.setText(_translate("Account", "Type the password for the username"))
        self.but_rem_2.setText(_translate("Account", "REMOVE"))
        self.but_back_2.setText(_translate("Account", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Account = QtWidgets.QMainWindow()
    ui = Ui_Account()
    ui.setupUi(Account)
    Account.show()
    sys.exit(app.exec_())


